import { MaterialCommunityIcons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { FlatList, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { menu } from "../../../src/data";
import { useCart } from "../../../src/store/cart";
import { colors } from "../../../src/theme";
export default function OrderScreen() {
  const { tableId } = useLocalSearchParams(); const [query, setQuery] = useState(""); const [category, setCategory] = useState("All");
  const { items, add, remove, total, clear } = useCart(); const filtered = menu.filter((x) => (category === "All" || x.category === category) && x.name.toLowerCase().includes(query.toLowerCase()));
  return <SafeAreaView style={s.page}><View style={s.header}><Pressable onPress={() => router.back()}><MaterialCommunityIcons name="arrow-left" size={26} /></Pressable><View><Text style={s.title}>Table {String(tableId).padStart(2, "0")}</Text><Text style={s.sub}>New order</Text></View><View style={{ width: 26 }} /></View>
    <View style={s.search}><MaterialCommunityIcons name="magnify" size={22} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search dishes..." style={{ flex: 1 }} /></View>
    <FlatList horizontal data={["All", "Starters", "Mains", "Drinks", "Desserts"]} keyExtractor={(x) => x} showsHorizontalScrollIndicator={false} style={{ maxHeight: 54 }} renderItem={({ item }) => <Pressable onPress={() => setCategory(item)} style={[s.chip, category === item && s.chipActive]}><Text style={{ color: category === item ? "white" : colors.ink, fontWeight: "700" }}>{item}</Text></Pressable>} />
    <FlatList data={filtered} keyExtractor={(x) => x.id} contentContainerStyle={{ paddingBottom: items.length ? 120 : 20 }} renderItem={({ item }) => { const count = items.find((x) => x.id === item.id)?.quantity ?? 0; return <View style={s.food}><View style={s.foodEmoji}><Text style={{ fontSize: 36 }}>{item.emoji}</Text></View><View style={{ flex: 1 }}><Text style={s.foodName}>{item.name}</Text><Text style={s.desc}>{item.description}</Text><Text style={s.price}>₹{item.price}</Text></View>{count ? <View style={s.stepper}><Pressable onPress={() => remove(item.id)}><Text style={s.step}>−</Text></Pressable><Text style={s.count}>{count}</Text><Pressable onPress={() => add(item)}><Text style={s.step}>+</Text></Pressable></View> : <Pressable style={s.add} onPress={() => add(item)}><Text style={s.addText}>ADD</Text></Pressable>}</View>; }} />
    {!!items.length && <View style={s.cart}><View><Text style={s.cartSmall}>{items.reduce((n, x) => n + x.quantity, 0)} DISHES</Text><Text style={s.cartTotal}>₹{total()}</Text></View><Pressable style={s.submit} onPress={() => { clear(); router.replace("/(app)/tables"); }}><Text style={s.submitText}>Send to kitchen</Text><MaterialCommunityIcons name="arrow-right" size={20} color="white" /></Pressable></View>}
  </SafeAreaView>;
}
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.cream, paddingHorizontal: 18 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 16 }, title: { fontSize: 22, fontWeight: "900", color: colors.ink, textAlign: "center" }, sub: { color: colors.muted, textAlign: "center" }, search: { flexDirection: "row", gap: 10, alignItems: "center", backgroundColor: "white", borderWidth: 1, borderColor: colors.border, borderRadius: 16, paddingHorizontal: 14, height: 50 }, chip: { paddingHorizontal: 17, paddingVertical: 10, borderRadius: 22, marginRight: 9, marginTop: 10, backgroundColor: "white" }, chipActive: { backgroundColor: colors.ink }, food: { flexDirection: "row", alignItems: "center", gap: 13, backgroundColor: "white", borderRadius: 20, padding: 13, marginTop: 12, borderWidth: 1, borderColor: colors.border }, foodEmoji: { width: 74, height: 74, borderRadius: 18, backgroundColor: "#FFF0E6", alignItems: "center", justifyContent: "center" }, foodName: { fontSize: 16, fontWeight: "800", color: colors.ink }, desc: { color: colors.muted, fontSize: 12, marginTop: 3 }, price: { color: colors.brand, fontWeight: "900", marginTop: 7 }, add: { borderWidth: 1.5, borderColor: colors.brand, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10 }, addText: { color: colors.brand, fontWeight: "900" }, stepper: { flexDirection: "row", alignItems: "center", gap: 10 }, step: { color: colors.brand, fontSize: 24, fontWeight: "800" }, count: { fontWeight: "900" }, cart: { position: "absolute", left: 16, right: 16, bottom: 12, backgroundColor: colors.ink, borderRadius: 20, padding: 14, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, cartSmall: { color: "#CFC5BF", fontSize: 10, fontWeight: "800" }, cartTotal: { color: "white", fontSize: 21, fontWeight: "900" }, submit: { flexDirection: "row", gap: 8, alignItems: "center", backgroundColor: colors.brand, borderRadius: 14, paddingHorizontal: 16, paddingVertical: 13 }, submitText: { color: "white", fontWeight: "800" } });
