import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useMutation, useQuery } from "@tanstack/react-query";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Alert, FlatList, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { api } from "../../../src/api/client";
import { useCart } from "../../../src/store/cart";
import { colors } from "../../../src/theme";
type Dish = { id: string; name: string; description: string; category: string; price: number; enabled: boolean; imageUrl?: string };
export default function OrderScreen() {
  const { tableId, tableName } = useLocalSearchParams<{ tableId: string; tableName: string }>(); const [query, setQuery] = useState("");
  const { items, add, remove, total, clear } = useCart();
  const { data = [] } = useQuery({ queryKey: ["menu"], queryFn: () => api<Dish[]>("/menu") });
  const submit = useMutation({ mutationFn: () => api("/orders", { method: "POST", body: JSON.stringify({ tableId, idempotencyKey: `${Date.now()}-${Math.random()}`, items: items.map((x) => ({ menuItemId: x.id, quantity: x.quantity, note: x.note })) }) }), onSuccess: () => { clear(); Alert.alert("Order sent", "The kitchen received your order."); router.replace("/(app)/tables"); }, onError: (e) => Alert.alert("Could not send order", e.message) });
  const filtered = data.filter((x) => x.enabled && x.name.toLowerCase().includes(query.toLowerCase()));
  return <SafeAreaView style={s.page}><View style={s.header}><Pressable onPress={() => router.back()}><MaterialCommunityIcons name="arrow-left" size={26} /></Pressable><Text style={s.title}>{tableName ?? "Table"}</Text><View style={{ width: 26 }} /></View><View style={s.search}><MaterialCommunityIcons name="magnify" size={22} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search food..." style={{ flex: 1 }} /></View>
    <FlatList data={filtered} keyExtractor={(x) => x.id} contentContainerStyle={{ paddingBottom: items.length ? 115 : 20 }} renderItem={({ item }) => { const count = items.find((x) => x.id === item.id)?.quantity ?? 0; const cartItem = { id: item.id, name: item.name, price: item.price }; return <View style={s.food}><View style={s.emoji}><MaterialCommunityIcons name="food" size={31} color={colors.brand} /></View><View style={{ flex: 1 }}><Text style={s.foodName}>{item.name}</Text><Text style={s.desc}>{item.description}</Text><Text style={s.price}>₹{(item.price / 100).toFixed(0)}</Text></View>{count ? <View style={s.stepper}><Pressable onPress={() => remove(item.id)}><Text style={s.step}>−</Text></Pressable><Text style={s.count}>{count}</Text><Pressable onPress={() => add(cartItem)}><Text style={s.step}>+</Text></Pressable></View> : <Pressable style={s.add} onPress={() => add(cartItem)}><Text style={s.addText}>ADD</Text></Pressable>}</View>; }} />
    {!!items.length && <View style={s.cart}><View><Text style={s.cartSmall}>{items.reduce((n, x) => n + x.quantity, 0)} DISHES</Text><Text style={s.cartTotal}>₹{(total() / 100).toFixed(0)}</Text></View><Pressable style={s.submit} onPress={() => submit.mutate()}><Text style={s.submitText}>{submit.isPending ? "Sending…" : "Send order"}</Text></Pressable></View>}
  </SafeAreaView>;
}
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.cream, paddingHorizontal: 18 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 16 }, title: { fontSize: 22, fontWeight: "900", color: colors.ink }, search: { flexDirection: "row", gap: 10, alignItems: "center", backgroundColor: "white", borderWidth: 1, borderColor: colors.border, borderRadius: 16, paddingHorizontal: 14, height: 50, marginBottom: 4 }, food: { flexDirection: "row", alignItems: "center", gap: 13, backgroundColor: "white", borderRadius: 20, padding: 13, marginTop: 12, borderWidth: 1, borderColor: colors.border }, emoji: { width: 66, height: 66, borderRadius: 18, backgroundColor: "#FFF0E6", alignItems: "center", justifyContent: "center" }, foodName: { fontSize: 16, fontWeight: "800", color: colors.ink }, desc: { color: colors.muted, fontSize: 12, marginTop: 3 }, price: { color: colors.brand, fontWeight: "900", marginTop: 7 }, add: { borderWidth: 1.5, borderColor: colors.brand, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10 }, addText: { color: colors.brand, fontWeight: "900" }, stepper: { flexDirection: "row", alignItems: "center", gap: 10 }, step: { color: colors.brand, fontSize: 24, fontWeight: "800" }, count: { fontWeight: "900" }, cart: { position: "absolute", left: 16, right: 16, bottom: 12, backgroundColor: colors.ink, borderRadius: 20, padding: 14, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, cartSmall: { color: "#CFC5BF", fontSize: 10, fontWeight: "800" }, cartTotal: { color: "white", fontSize: 21, fontWeight: "900" }, submit: { backgroundColor: colors.brand, borderRadius: 14, paddingHorizontal: 18, paddingVertical: 13 }, submitText: { color: "white", fontWeight: "900" } });
