import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FlatList, Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
import type { ItemStatus } from "@restaurant/shared";
import { api } from "../../src/api/client";
import { colors } from "../../src/theme";
type Order = { id: string; tableId: string; tableName: string; batches: { type: "original" | "added_later"; items: { id: string; status: ItemStatus }[] }[] };
const nextStatus: Partial<Record<ItemStatus, ItemStatus>> = { pending: "started", started: "ready", ready: "completed" };
export default function Kitchen() {
  const client = useQueryClient();
  const { data = [], isLoading, error, refetch } = useQuery({ queryKey: ["orders"], queryFn: () => api<Order[]>("/orders"), refetchInterval: 5000 });
  const update = useMutation({ mutationFn: ({ id, status }: { id: string; status: ItemStatus }) => api(`/order-items/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }), onSuccess: () => client.invalidateQueries({ queryKey: ["orders"] }) });
  return <SafeAreaView style={s.page}><Text style={s.eyebrow}>LIVE KITCHEN</Text><Text style={s.title}>Order queue</Text><Text style={s.sub}>Move every dish from pending to completed.</Text>
    {isLoading ? <Text style={s.message}>Loading orders…</Text> : error ? <Text onPress={() => refetch()} style={s.error}>{error.message} · Tap to retry</Text> : <FlatList data={data} keyExtractor={(x) => x.id} renderItem={({ item }) => <View style={s.card}><View style={s.top}><Text style={s.table}>Order {item.id.slice(0, 6)}</Text><Text style={s.id}>{item.tableName}</Text></View>{item.batches.map((batch, i) => <View key={`${batch.type}-${i}`} style={s.batch}><Text style={[s.badge, batch.type === "added_later" && { color: colors.blue }]}>{batch.type === "added_later" ? "ADDED LATER" : "ORIGINAL"}</Text>{batch.items.map((dish, n) => { const next = nextStatus[dish.status]; return <View style={s.dish} key={dish.id}><View><Text style={s.dishName}>Dish {n + 1}</Text><Text style={s.status}>{dish.status}</Text></View>{next && <Pressable style={s.action} onPress={() => update.mutate({ id: dish.id, status: next })}><Text style={s.actionText}>{next === "started" ? "Start" : next === "ready" ? "Ready" : "Complete"}</Text></Pressable>}</View>; })}</View>)}</View>} />}
  </SafeAreaView>;
}
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.cream, padding: 18 }, eyebrow: { color: colors.brand, fontWeight: "900", letterSpacing: 1.4, fontSize: 11, marginTop: 18 }, title: { fontSize: 32, fontWeight: "900", color: colors.ink, marginTop: 4 }, sub: { color: colors.muted, marginBottom: 12 }, card: { backgroundColor: "white", padding: 18, borderRadius: 22, marginTop: 12, borderWidth: 1, borderColor: colors.border }, top: { flexDirection: "row", justifyContent: "space-between" }, table: { fontSize: 19, fontWeight: "900", color: colors.ink }, id: { color: colors.muted }, batch: { marginTop: 14, paddingTop: 12, borderTopWidth: 1, borderTopColor: colors.border }, badge: { color: colors.brand, fontSize: 11, fontWeight: "900" }, dish: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 12 }, dishName: { color: colors.ink, fontWeight: "800" }, status: { color: colors.muted, textTransform: "capitalize", marginTop: 2 }, action: { backgroundColor: colors.ink, borderRadius: 11, paddingHorizontal: 14, paddingVertical: 9 }, actionText: { color: "white", fontWeight: "900" }, message: { textAlign: "center", color: colors.muted, marginTop: 30 }, error: { textAlign: "center", color: colors.brand, marginTop: 30 } });
