import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Alert, FlatList, Modal, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { api } from "../../src/api/client";
import { useSession } from "../../src/store/session";
import { colors } from "../../src/theme";
type Dish = { id: string; name: string; category: string; categoryId: string; description: string; price: number; enabled: boolean };
type Category = { id: string; name: string };
export default function Menu() {
  const role = useSession((s) => s.role); const editable = role === "chef" || role === "admin"; const queryClient = useQueryClient();
  const { data = [] } = useQuery({ queryKey: ["menu"], queryFn: () => api<Dish[]>("/menu") });
  const { data: categories = [] } = useQuery({ queryKey: ["categories"], queryFn: () => api<Category[]>("/categories") });
  const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [price, setPrice] = useState(""); const [description, setDescription] = useState("");
  const create = useMutation({ mutationFn: () => api("/menu", { method: "POST", body: JSON.stringify({ name, description, price: Math.round(Number(price) * 100), categoryId: categories[0]?.id }) }), onSuccess: () => { setOpen(false); setName(""); setPrice(""); setDescription(""); queryClient.invalidateQueries({ queryKey: ["menu"] }); }, onError: (e) => Alert.alert("Could not save", e.message) });
  return <SafeAreaView style={s.page}><View style={s.header}><View><Text style={s.eyebrow}>RESTAURANT MENU</Text><Text style={s.title}>Dishes</Text></View>{editable && <Pressable style={s.new} onPress={() => setOpen(true)}><MaterialCommunityIcons name="plus" size={20} color="white" /><Text style={s.newText}>New dish</Text></Pressable>}</View>
    <FlatList data={data} keyExtractor={(x) => x.id} renderItem={({ item }) => <View style={s.item}><View style={s.icon}><MaterialCommunityIcons name="food" size={26} color={colors.brand} /></View><View style={{ flex: 1 }}><Text style={s.name}>{item.name}</Text><Text style={s.category}>{item.category} · ₹{(item.price / 100).toFixed(0)}</Text></View><View style={[s.dot, { backgroundColor: item.enabled ? colors.green : colors.muted }]} /></View>} />
    <Modal visible={open} transparent animationType="slide"><View style={s.overlay}><View style={s.sheet}><Text style={s.sheetTitle}>Add menu item</Text><TextInput style={s.input} placeholder="Dish name" value={name} onChangeText={setName} /><TextInput style={s.input} placeholder="Description" value={description} onChangeText={setDescription} /><TextInput style={s.input} keyboardType="numeric" placeholder="Price in ₹" value={price} onChangeText={setPrice} /><Pressable style={s.save} onPress={() => create.mutate()}><Text style={s.saveText}>Save dish</Text></Pressable><Pressable onPress={() => setOpen(false)}><Text style={s.cancel}>Cancel</Text></Pressable></View></View></Modal>
  </SafeAreaView>;
}
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.cream, padding: 18 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 18, marginBottom: 10 }, eyebrow: { color: colors.brand, fontWeight: "900", letterSpacing: 1.3, fontSize: 11 }, title: { fontSize: 32, fontWeight: "900", color: colors.ink }, new: { flexDirection: "row", gap: 5, backgroundColor: colors.brand, padding: 12, borderRadius: 14 }, newText: { color: "white", fontWeight: "800" }, item: { flexDirection: "row", gap: 14, alignItems: "center", backgroundColor: "white", borderRadius: 18, padding: 15, marginTop: 10, borderWidth: 1, borderColor: colors.border }, icon: { width: 48, height: 48, borderRadius: 15, backgroundColor: "#FFF0E6", alignItems: "center", justifyContent: "center" }, name: { color: colors.ink, fontSize: 16, fontWeight: "800" }, category: { color: colors.muted, marginTop: 4 }, dot: { width: 10, height: 10, borderRadius: 5 }, overlay: { flex: 1, backgroundColor: "#0008", justifyContent: "flex-end" }, sheet: { backgroundColor: colors.cream, padding: 22, borderTopLeftRadius: 28, borderTopRightRadius: 28 }, sheetTitle: { fontSize: 24, fontWeight: "900", color: colors.ink, marginBottom: 10 }, input: { height: 50, backgroundColor: "white", borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingHorizontal: 14, marginTop: 10 }, save: { backgroundColor: colors.brand, borderRadius: 14, padding: 15, marginTop: 16 }, saveText: { color: "white", textAlign: "center", fontWeight: "900" }, cancel: { textAlign: "center", color: colors.muted, padding: 14 } });
