import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, FlatList, Modal, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { api } from "../../src/api/client";
import { useSession } from "../../src/store/session";
import { colors } from "../../src/theme";
type Account = { username: string; role: string; name: string };
export default function Settings() {
  const role = useSession((s) => s.role); const clear = useSession((s) => s.clearRole); const client = useQueryClient(); const [open, setOpen] = useState(false); const [tableName, setTableName] = useState("");
  const { data: accounts = [] } = useQuery({ queryKey: ["accounts"], queryFn: () => api<Account[]>("/accounts"), enabled: role === "admin" });
  const addTable = useMutation({ mutationFn: () => api("/tables", { method: "POST", body: JSON.stringify({ name: tableName }) }), onSuccess: () => { setOpen(false); setTableName(""); client.invalidateQueries({ queryKey: ["tables"] }); }, onError: (e) => Alert.alert("Could not add table", e.message) });
  const canManage = role !== "customer";
  return <SafeAreaView style={s.page}><Text style={s.eyebrow}>OPERATIONS</Text><Text style={s.title}>Settings</Text><View style={s.role}><MaterialCommunityIcons name="account-circle" size={42} color="white" /><View><Text style={s.label}>Signed in as</Text><Text style={s.value}>{role}</Text></View></View>
    {canManage && <Pressable style={s.setting} onPress={() => setOpen(true)}><MaterialCommunityIcons name="table-chair" size={25} /><View style={{ flex: 1 }}><Text style={s.settingTitle}>Add table</Text><Text style={s.settingBody}>Create another dining table</Text></View></Pressable>}
    {role === "admin" && <View style={s.accounts}><Text style={s.section}>Initial accounts</Text><FlatList data={accounts} keyExtractor={(x) => x.username} renderItem={({ item }) => <View style={s.account}><Text style={s.accountName}>{item.name}</Text><Text style={s.accountRole}>{item.username} · {item.role}</Text></View>} /></View>}
    <Pressable style={s.switch} onPress={() => { clear(); router.replace("/"); }}><Text style={s.switchText}>Sign out</Text></Pressable>
    <Modal visible={open} transparent animationType="slide"><View style={s.overlay}><View style={s.sheet}><Text style={s.sheetTitle}>Add table</Text><TextInput style={s.input} value={tableName} onChangeText={setTableName} placeholder="Example: T13 or Patio 3" /><Pressable style={s.save} onPress={() => addTable.mutate()}><Text style={s.saveText}>Create table</Text></Pressable><Pressable onPress={() => setOpen(false)}><Text style={s.cancel}>Cancel</Text></Pressable></View></View></Modal>
  </SafeAreaView>;
}
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.cream, padding: 18 }, eyebrow: { color: colors.brand, fontWeight: "900", letterSpacing: 1.3, fontSize: 11, marginTop: 18 }, title: { color: colors.ink, fontSize: 32, fontWeight: "900" }, role: { flexDirection: "row", gap: 14, alignItems: "center", backgroundColor: colors.ink, padding: 18, borderRadius: 20, marginVertical: 18 }, label: { color: "#CFC5BF", fontSize: 12 }, value: { color: "white", fontWeight: "900", fontSize: 19, textTransform: "capitalize" }, setting: { flexDirection: "row", alignItems: "center", gap: 14, backgroundColor: "white", padding: 17, borderRadius: 17, borderWidth: 1, borderColor: colors.border }, settingTitle: { color: colors.ink, fontWeight: "800" }, settingBody: { color: colors.muted, fontSize: 12, marginTop: 3 }, accounts: { marginTop: 18, maxHeight: 260 }, section: { color: colors.ink, fontSize: 18, fontWeight: "900", marginBottom: 8 }, account: { backgroundColor: "white", padding: 13, borderRadius: 14, marginBottom: 8 }, accountName: { color: colors.ink, fontWeight: "800" }, accountRole: { color: colors.muted, marginTop: 3 }, switch: { borderWidth: 1.5, borderColor: colors.brand, padding: 15, borderRadius: 15, marginTop: "auto" }, switchText: { color: colors.brand, textAlign: "center", fontWeight: "900" }, overlay: { flex: 1, backgroundColor: "#0008", justifyContent: "flex-end" }, sheet: { backgroundColor: colors.cream, padding: 22, borderTopLeftRadius: 28, borderTopRightRadius: 28 }, sheetTitle: { fontSize: 24, fontWeight: "900", color: colors.ink }, input: { height: 50, backgroundColor: "white", borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingHorizontal: 14, marginTop: 14 }, save: { backgroundColor: colors.brand, borderRadius: 14, padding: 15, marginTop: 16 }, saveText: { color: "white", textAlign: "center", fontWeight: "900" }, cancel: { textAlign: "center", color: colors.muted, padding: 14 } });
